# Tirgul 3

## Add nice equations using LaTEX syntax in Markdown
### Sphere or Quadratic equations::
$ x^2 + y^2 = z^2 \\$
$ \\ x_1,_2 =  \frac{- b\pm \sqrt{b^2-4ac}}{2a} $

# master chef
# https://www.facebook.com/MicrosoftRnDil/videos/1090576338109340/

In [1]:
# get file from web
import pandas as pd
url = "https://data.humdata.org/hxlproxy/api/data-preview.csv?url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSEGISandData%2FCOVID-19%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series%2Ftime_series_covid19_deaths_global.csv"
cuvid19Deaths = pd.read_csv(url)
cuvid19Deaths.head()

Province/State Country/Region       Lat       Long  1/22/20  1/23/20  \
0            NaN    Afghanistan  33.93911  67.709953        0        0   
1            NaN        Albania  41.15330  20.168300        0        0   
2            NaN        Algeria  28.03390   1.659600        0        0   
3            NaN        Andorra  42.50630   1.521800        0        0   
4            NaN         Angola -11.20270  17.873900        0        0   

   1/24/20  1/25/20  1/26/20  1/27/20  ...  6/4/21  6/5/21  6/6/21  6/7/21  \
0        0        0        0        0  ...    3068    3104    3145    3187   
1        0        0        0        0  ...    2451    2451    2451    2452   
2        0        0        0        0  ...    3504    3510    3518    3527   
3        0        0        0        0  ...     127     127     127     127   
4        0        0        0        0  ...     788     794     797     800   

   6/8/21  6/9/21  6/10/21  6/11/21  6/12/21  6/13/21  
0    3251    3305     3356     3412     3449     3527  
1    2452    2452     2452     2453     2453     2453  
2    3537    3544     3552     3560     3565     3571  
3     127     127      127      127      127      127  
4     803     811      815      819      825      831  

[5 rows x 513 columns]

In [2]:
# get Israel data
cuvid19Deaths[cuvid19Deaths['Country/Region'].str.contains("Israel")]

Province/State Country/Region        Lat       Long  1/22/20  1/23/20  \
152            NaN         Israel  31.046051  34.851612        0        0   

     1/24/20  1/25/20  1/26/20  1/27/20  ...  6/4/21  6/5/21  6/6/21  6/7/21  \
152        0        0        0        0  ...    6417    6418    6418    6418   

     6/8/21  6/9/21  6/10/21  6/11/21  6/12/21  6/13/21  
152    6418    6418     6428     6428     6428     6430  

[1 rows x 513 columns]

In [3]:
data = pd.read_csv('titanic_short.csv')
data.head()

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male

In [4]:
data['age']

0     29.0000
1      2.0000
2     30.0000
3     25.0000
4      0.9167
5     47.0000
6     63.0000
7     39.0000
8     58.0000
9     71.0000
10    47.0000
11    19.0000
12        NaN
13        NaN
14        NaN
15    50.0000
16    24.0000
17    36.0000
18    37.0000
19        NaN
20    26.0000
21    25.0000
22        NaN
23    19.0000
24    28.0000
25        NaN
26    39.0000
27    30.0000
28    58.0000
29        NaN
Name: age, dtype: float64

In [5]:
# is null - isna
dataIsNull = pd.isnull(data['age'])
dataIsNull

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14     True
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28    False
29     True
Name: age, dtype: bool

In [6]:
# isna is exactly the same (due to historical reasons related to 'R' language)
dataIsna = pd.isna(data['age'])
dataIsna

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14     True
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28    False
29     True
Name: age, dtype: bool

In [9]:
# we can present the data at these null rows
filteredData = data[pd.isna(data['age'])]
filteredData

pclass  survived  age     sex
12    1st         1  NaN  female
13    1st         1  NaN    male
14    1st         0  NaN    male
19    1st         1  NaN  female
22    1st         1  NaN    male
25    1st         0  NaN    male
29    1st         0  NaN    male

In [10]:
# What if we want to only the cell with no null:
# we could us the ~ operate
filteredData = data[~pd.isna(data['age'])]
filteredData.head(13)

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
15    1st         1  50.0000  female

In [11]:
# or the notnull command
filteredData = data[pd.notnull(data['age'])]
filteredData.head(13)

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
15    1st         1  50.0000  female

In [26]:
# Mean
dataAge = filteredData['age']
dataAge.mean()

34.90942173913044

In [27]:
dataAge.min()

0.9167

In [28]:
dataAge.max()

71.0

In [29]:
dataAge.median()

30.0

## Numpy
Matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr*arr)

[ 1  4  9 16 25]


In [31]:
#### vector multiplication (AKA dot producdt)
print("arr.dot(arr)\t=",arr.dot(arr))
# or by 
print("arr@arr\t\t=",arr@arr)


arr.dot(arr)	= 55
arr@arr		= 55


In [32]:
# create ones matrix of specific size:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# self excercise: create zeros matrix of specific size 4X3:






In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# The I matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# self excercise: create the following 3X3 diagonal matrix
#  [1., 0., 0.],
#  [0., 2., 0.],
#  [0., 0., 3.]








In [42]:
print([1,2,3]*np.eye(3))

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [43]:
# Another Way
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [44]:
# random
e = np.random.random((2,4)) 
print(e)

[[0.74738624 0.61785783 0.22894666 0.82370343]
 [0.45945422 0.05077788 0.30786927 0.38762231]]


In [45]:
# append
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13, 14, 15])
arr3 = np.append(arr1,arr2)
print(arr3)


[ 1  2  3  4  5 11 12 13 14 15]


In [46]:
# we can add arrays of same shape
print(arr1+arr2)

[12 14 16 18 20]


In [47]:
# However arrays must have same size
arr3 = np.array([1,2])
print(arr1+arr3) # ERROR

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [ ]:
# self excercise: Assume hypothethical case where you wish for each student to calculate average of the highest 5 grades out of 6 student's assignment
# step 1. generate 10X6 random integer numbers between 70 to 100 to represent students grades
# step 2. calculate mean of top 5 grades for each student








In [36]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print(grades)

[[74 79 86 85 91 74]
 [95 73 78 86 96 87]
 [83 82 95 74 91 89]
 [83 72 73 93 82 83]
 [90 75 76 70 72 85]
 [93 86 92 79 93 76]
 [92 93 88 72 84 89]
 [78 80 95 74 88 90]
 [79 81 81 89 77 99]
 [74 88 90 73 95 84]]


In [38]:
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg
top5Avg = top5Avg.reshape(len(top5Avg),1) # for display purpose
print(top5Avg)

[[83. ]
 [88.4]
 [88. ]
 [82.8]
 [79.6]
 [88.6]
 [89.2]
 [86.2]
 [85.8]
 [86.2]]
